### PR TITLE
Remodel `DetailedItinerariesComputer`

### LINKED ISSUE #278: Add option to `DetailedItineraries()` to retain geometry
R5r’s `detailed_itineraries` can return the geometry of the travelled path. Let’s implement this in r5py, too

### LINKED ISSUE #280: Detailed Itineraries Computer returns multiple records for same OD pair
Running the detailed itineraries computer returns multiple rows for the same OD pair, some of which have no variations in the routes used. Some documentation might be needed to clarify how to interpret (and handle) this output.

Image below:

image

### LINKED ISSUE #288: Make travel time column names consistent betwen `TravelTimeMatrixComputer` and `DetailedItinerariesComputer`
Currently, `DetailedItinerariesComputer` returns the total travel time column as `total_time`, while `TravelTimeMatrixComputer` uses travel time. For consistency these should match.

### LINKED ISSUE #289: Fail with a more meaningful error message when snapping fails for all points in destinations or origins
Currently, when choosing `snap_to_network=True` with, e.g., `TravelTimeMatrix`, r5py raises a warning if it cannot snap all points to the network. However, if it fails to snap *any* point (leaving an empty `destinations` or `origins`), routing can still proceed, but results in the rather cryptic exception `ValueError: No objects to concatenate`. 

Let’s add a sanity check before carrying out the actual computations

### PR DESCRIPTION
**Pull request by christophfink**
This PR addresses several issues with `DetailedItinerariesComputer`:

- include the trip’s geometry in the results (fixes #278 )
- align the output with r5r’s `detailed_itinerary_computer` (but keep Pythonic) (fixes #280 , fixes #288 )
- fail if snapping eliminates all origin/destination candidate points (also affects `TravelTimeMatrixComputer`, fixes #289)

### CODE REVIEW

**Comment by christophfink** [comment]
@HTenkanen @wklumpen : documentation will be part of PR #238 , see attached jupyter notebooks for example code and output

Note that vanilla R5 discards the geometries of GTFS routes. You can use a patched R5, such as our Helsinki-mod at https://github.com/DigitalGeographyLab/r5/releases/tag/v6.9-post16-g1054c1e-20230619 , to get proper geometry output. (this goes into the documentation, of course)

[detailed_itineraries.ipynb.zip](https://github.com/r5py/r5py/files/11962500/detailed_itineraries.ipynb.zip)

**Review by wklumpen — COMMENTED** [review]
Might be useful to do a quick walkthrough on the structural refactoring you did for the itineraries - can do at our next call?

**Comment by christophfink** [comment]
> Might be useful to do a quick walkthrough on the structural refactoring you did for the itineraries - can do at our next call?

It would be nice to step faster than that - our call is on the first day of my holidays, it would be great to have a release by then.

The jupyter notebooks are fairly self-explaining on how things work per-se. Please have a quick look and shoot questions in Slack or here :)

**Comment by christophfink** [comment]
Also, while the code still needs some refactoring, eventually (e.g., we could do with an own `StreetRouter` class on the Python side), that needs some planning and thinking, and it would be nice to have this monster pull request off the desk to, next, concentrate on the documentation part

**Review by wklumpen — APPROVED** [review]

**Comment by wklumpen** [comment]
It's a behemoth alright, but it does seem to be passing tests and I get the general sense of the refactor.

**Pull request merged**
