### PR TITLE
Make the JVM starting/Java imports more explicit, and call start_jvm() where it is needed, not everywhere

### LINKED ISSUE #94: Reduce reliance on module loading side effects
Currently, `import jvm` starts the JVM without calling anything else. This is not great, in a way, and we should maybe introduce a function `r5py.util.jvm.start_jvm()` that gets called in the relevant source files (before importing java classes; restriction connected to jpype’s architecture), and that ‘fails gracefully’ if the JVM has been started already. 

This would also help with the import order of relative imports (make the order less significant).

### PR DESCRIPTION
**Pull request by christophfink**
closes #94

### CODE REVIEW

**Comment by christophfink** [comment]
so because the last commit has ‘[skip ci]’ (I added it only after opening the pull request), the checks are skipped altogether?

**Comment by christophfink** [comment]
The code passes tests locally, please have a quick review first @HTenkanen , then we might get another commit, anyway ;)

**Comment by HTenkanen** [comment]
@christophfink Yes, can take a look later today. 👍🏻 Now heading for PhD defense of one of our students 🎩

**Comment by christophfink** [comment]
Sorry for rewriting history, pushed to wrong branch

**Review by HTenkanen — APPROVED** [review]
Looks good! 👍🏻 Don't understand much about the details of Jpype stuff in `jvm.py` but everything works fine, so can't complain. 😄

**Pull request merged**
