### PR TITLE
switch to mybinder.org for binder links

### LINKED ISSUE #344: Binder link does not work as expected
The Binder button on our documentation does not direct correctly to GESIS Notebooks, but it only takes you to the home page of GESIS: https://notebooks.gesis.org/binder/

Something going on probably with the Binder configuration in the [conf.py](https://github.com/r5py/r5py/blob/main/docs/conf.py)

### PR DESCRIPTION
**Pull request by christophfink**
closes #344

### CODE REVIEW

**Comment by christophfink** [comment]
To test things, copy the link of the binder button and replace `r5py/r5py` with `christophfink/r5py` - haven’t managed yet to find the time to adapt the repository urls for pull requests (the commit is included in the url automatically)

**Comment by christophfink** [comment]
> To test things, copy the link of the binder button and replace `r5py/r5py` with `christophfink/r5py` - haven’t managed yet to find the time to adapt the repository urls for pull requests (the commit is included in the url automatically)

https://mybinder.org/v2/gh/christophfink/r5py/2a32dd8?urlpath=tree/docs/user-guide/user-manual/quickstart.md
https://mybinder.org/v2/gh/christophfink/r5py/2a32dd8?urlpath=tree/docs/user-guide/user-manual/travel-time-matrices.md
https://mybinder.org/v2/gh/christophfink/r5py/2a32dd8?urlpath=tree/docs/user-guide/user-manual/detailed-itineraries.md
https://mybinder.org/v2/gh/christophfink/r5py/2a32dd8?urlpath=tree/docs/user-guide/user-manual/advanced-use.md

**Comment by christophfink** [comment]
RAM is not enough for all examples it seems :/

**Comment by christophfink** [comment]
> RAM is not enough for all examples it seems :/

Not sure what to do about this now. Our example cases are already shrunk down to a minimum (see also Rafael’s comments in Slack where he wished for larger study areas), it’s just that 4GiB are just too little

**Comment by christophfink** [comment]
On the bright side: `advanced-use.md` works perfectly :) I’m now experimenting whether further limiting the JVM heap would help

**Comment by christophfink** [comment]
Or is it maybe the execution time of individual cells that makes it kill the kernel?

**Comment by HTenkanen** [comment]
I have been struggling with this issue, and haven't found a cloud-based solution thus far. :/

One option that might worth exploring is Jupyter Lite: https://jupyterlite.readthedocs.io/en/latest/

However, as we are depending on Java, I'm a bit sceptical whether it can be done.. But who knows!

**Comment by christophfink** [comment]
JupyterLite looks very interesting, but, indeed, won't work for our use case :/

**Comment by christophfink** [comment]
My suggestion would be to still merge this pull request, as the specific url for the gesis binder hub ceased to exist, but the mybinder.org seems to work, at least theoretically. Not sure whether we should take the binder links away (that would be a separate issue); I’d think we at least should not advertise it too prominently for the time being.

**Comment by christophfink** [comment]
And now, of course, I’ve managed to make it work. I’ll take another closer look and see what has changed :)

**Comment by HTenkanen** [comment]
@christophfink Is this now ready for review? You got the examples working? 🙂

**Comment by christophfink** [comment]
> @christophfink Is this now ready for review? You got the examples working? 🙂

yes

**Pull request merged**
