### PR TITLE
Departure Time Window Default and Warning

### PR DESCRIPTION
**Pull request by wklumpen**
See #292

### CODE REVIEW

**Comment by christophfink** [comment]
The test data sets don’t match any more (of course, arguments changed). Two options: 1) change the tests to set `departure_time_window = datetime.timedelta(hours=1)` to mimick the old default behaviour, or 2) regenerate the test comparison data sets

**Comment by wklumpen** [comment]
I would vote making the tests fixed time windows

**Comment by christophfink** [comment]
> I would vote making the tests fixed time windows

I’m fine with either way, choose what is easier for you :)

**Review by christophfink — APPROVED** [review]
Looks good :)

**Pull request merged**
