### PR TITLE
Proposed license change (MIT in addition to GPLv3)

### PR DESCRIPTION
**Pull request by christophfink**

### CODE REVIEW

**Comment by HTenkanen** [comment]
Here is some discussion why and how dual-license work:
https://softwareengineering.stackexchange.com/questions/139663/confusion-about-dual-license-mit-gpl-javascript-for-use-on-my-website

**Review by HTenkanen — APPROVED** [review]
Looks great!

**Comment by HTenkanen** [comment]
@christophfink : By the way, not sure if you already know this, but if you add `[skip ci]` to commit message, you can skip the GA pipeline. For example, in this case we wouldn't have needed to run the tests.

**Comment by christophfink** [comment]
That's a great tip that I did not know! Thanks!

**Pull request merged**
