### PR TITLE
Use sphinx book theme with the docs

### LINKED ISSUE #14: A newer/fresher look for the docs?
@christophfink: RTD theme does what it should, but would it be good to use `sphinx_book_theme` which gives a bit fresher outlook for the docs? We use this theme in quite many places and it's quite nice. 🙂

### PR DESCRIPTION
**Pull request by HTenkanen**
Closes #14 
Relates to #32 

I now updated the theme of the docs and also created a simple logo based on r5r design, I hope @rafapereirabr @mvpsaraiva this is okay? I'm sure @christophfink wants to update the logo to a better one, but at least we have something for now. 

You can check how the documentation looks at the moment from here:
https://r5py-fork.readthedocs.io/en/issue_14/

### CODE REVIEW

**Review by christophfink — COMMENTED** [review]
Looks great, but can we stick (for the time being, at least) with running the notebooks when compiling the documentation?
Right now the link you shared does not have results, because the commit filters in .gitattributes strip out the outputs (on purpose, to keep the repository and commit history clean)

**Comment by HTenkanen** [comment]
Ahaa, right. Hmm, I think the RTD docs building shouldn't add anything to the commit history, so not sure why you need to strip out the ipynb outputs? Or is there something else I don't understand?

**Comment by christophfink** [comment]
When you build it locally before committing (which is a precondition for not having to run it on RTD), you’ll commit the output.

**Comment by HTenkanen** [comment]
Ahaa, so you don't want to have the tutorial notebooks being executed to have the outputs in commit history? I.e. keep the Notebook JSON files more clean?

**Comment by HTenkanen** [comment]
I'll reverse this to how it was (i.e. running the notebooks), but I guess we can continue thinking about this. 👍🏻

**Comment by christophfink** [comment]
> Ahaa, so you don't want to have the tutorial notebooks being executed to have the outputs in commit history? I.e. keep the Notebook JSON files more clean?

Yes, so that the changes to the notebooks are readable. Also prevents giant binary blobs (e.g., for figures).

**Comment by HTenkanen** [comment]
True, the size of the repo will be better handled in this way. 👍🏻

**Review by christophfink — APPROVED** [review]
Looks good!

**Comment by HTenkanen** [comment]
@christophfink Oops, did you check the docs? I think this is not working yet. I.e. the outputs in the Notebook are not printed out yet..

**Comment by HTenkanen** [comment]
I'm just figuring out what is going on.. I got some kind of execution error when the Notebook was being executed in RTD

**Comment by christophfink** [comment]
I had run into an error before that occurred when RTD seemed to hit the fair-use limit of the OpenStreetMap tileserver, is is that, again?

**Comment by christophfink** [comment]
Oh and yes :( I did not check the RTD build

**Comment by HTenkanen** [comment]
Not sure, what it is, but it seems to fail right after running the r5py codes. Here is the log:
image

So probably there is an issue with running the r5py in the RTD environment. Will test now, whether the outputs are rendered correctly if I just pass a Notebook with outputs in place.

**Comment by HTenkanen** [comment]
@christophfink Now tested building the docs in such a way that the outputs were in place, and it seems to work:
https://r5py-fork.readthedocs.io/en/issue_39/basic-usage.html

I.e. for some reason r5py is not running properly in the RTD system. Any ideas?

**Comment by christophfink** [comment]
```
Traceback (most recent call last):
  File "/home/christoph/.local/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/christoph/.local/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/christoph/.local/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/christoph/.local/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/christoph/.local/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/christoph/.local/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/christoph/.local/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from r5py import TransportNetwork

transport_network = TransportNetwork(
    "data/kantakaupunki.osm.pbf",
    [
        "data/GTFS.zip"
    ]
)
------------------

---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
File TransportNetwork.java:126, in com.conveyal.r5.transit.TransportNetwork.fromFiles()

File OSM.java:112, in com.conveyal.osmlib.OSM.<init>()

File DBMaker.java:701, in org.mapdb.DBMaker.make()

File DBMaker.java:758, in org.mapdb.DBMaker.makeEngine()

File DBMaker.java:971, in org.mapdb.DBMaker.extendStoreDirect()

File StoreDirect.java:207, in org.mapdb.StoreDirect.<init>()

File StoreDirect.java:253, in org.mapdb.StoreDirect.checkHeaders()

File Volume.java:424, in org.mapdb.Volume$ByteBufferVol.getInt()

Exception: Java Exception

The above exception was the direct cause of the following exception:

java.lang.ArrayIndexOutOfBoundsException  Traceback (most recent call last)
Input In [2], in <cell line: 3>()
      1 from r5py import TransportNetwork
----> 3 transport_network = TransportNetwork(
      4     "data/kantakaupunki.osm.pbf",
      5     [
      6         "data/GTFS.zip"
      7     ]
      8 )

File ~/Dokumente/Tools/r5py/docs/../src/r5py/r5/transport_network.py:61, in TransportNetwork.__init__(self, osm_pbf, gtfs, build_config)
     58 gtfs = [os.path.abspath(path) for path in gtfs]
     59 build_config = TransportNetworkBuilderConfig(**build_config)
     60 self._transport_network = (
---> 61     com.conveyal.r5.transit.TransportNetwork.fromFiles(
     62         java.lang.String(osm_pbf),
     63         java.util.ArrayList.of(gtfs),
     64         build_config
     65     )
     66 )
     67 self._transport_network.transitLayer.buildDistanceTables(None)

java.lang.ArrayIndexOutOfBoundsException: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
java.lang.ArrayIndexOutOfBoundsException: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
```

**Comment by christophfink** [comment]
Not quite sure what happens, and very puzzling that this crops up now all of a sudden

**Comment by HTenkanen** [comment]
Hmm, weird. So you are able to reproduce this on your own computer as well?

**Comment by christophfink** [comment]
yes, weirdly enough.

**Comment by christophfink** [comment]
I have meeting now, I’ll be back in an hour, and would then try to narrow it down at what commit this started happening. (or whether it’s some outside problem)

**Pull request merged**
