### PR TITLE
coverage testing, matrix testing

### PR DESCRIPTION
**Pull request by christophfink**
Work in progress (finishing my work day), but please comment, already.

This still needs a bit of work to produce a coverage badge that can be displayed in the README.md
On top of that, putting the pytest options into pyproject.toml might be smart; and the `coverage` module is worth a look.

### CODE REVIEW

**Comment by HTenkanen** [comment]
To be honest, I have never used tox for anything. I have found it somehow confusing to use. Not saying that we shouldn't use it, but I'm not a correct person to review those things as I'm not familiar with it.. 

I have used `.coveragerc` [configuration file](https://github.com/HTenkanen/pyrosm/blob/master/.coveragerc) and a codecov action which is part of the GA workflow in [tests.yaml](https://github.com/HTenkanen/pyrosm/blob/master/.github/workflows/tests.yaml)

**Comment by HTenkanen** [comment]
Here is some discussion about tox: https://discourse.jupyter.org/t/thoughts-on-using-tox/3497/10

**Comment by christophfink** [comment]
conftest.py is not a test, but a config file (used by many test frameworks, fixed filename)

**Comment by christophfink** [comment]
Going to read the discussion on tox tomorrow morning

**Comment by HTenkanen** [comment]
> conftest.py is not a test, but a config file (used by many test frameworks, fixed filename)

Ah, right 👍🏻

**Comment by christophfink** [comment]
@HTenkanen : Could you check whether this looks alright now?

**Comment by christophfink** [comment]
Is there any good mechanism to test Github Actions (except trial-and-error)?

**Review by HTenkanen — APPROVED** [review]
Looks good to me!

**Comment by HTenkanen** [comment]
Oof, these GAs are indeed quite annoying to debug..

**Pull request merged**
