### PR TITLE
Add possibility to use Binder for testing r5py

### LINKED ISSUE #34: Setup Binder environment for r5py
With the new theme, it would be very easy to launch a binder and test the tool immediately in a browser. We might want to try and setup that at some point. This requires a bit of testing because there are quite specific dependencies with this package (namely Java DK and r5)

### PR DESCRIPTION
**Pull request by HTenkanen**
Resolves #34

### CODE REVIEW

**Comment by HTenkanen** [comment]
@christophfink : Added now a possibility to test r5py with Binder. Tested it with local fork and it seems to work nicely 👍🏻 Although Binder seems to be a bit unstable at the moment, and building the environment takes long. With this PR also added missing r5py and openjdk dependencies from `r5py_distro.yaml`

**Comment by HTenkanen** [comment]
Btw. notice that the how the Binder is now configured, it won't work before it is merged to main. If you want to test it yourself, you can use the link from my fork:
https://mybinder.org/v2/gh/htenkanen/r5py/issue_34?urlpath=lab/tree/docs/basic-usage.ipynb

**Review by christophfink — APPROVED** [review]
I guess this looks okay (no idea, TBH). The binder link you shared, does *not* work for me, btw

**Comment by christophfink** [comment]
> I guess this looks okay (no idea, TBH). The binder link you shared, does _not_ work for me, btw

It does work, just had some third-party scripts blocked it needed

**Comment by HTenkanen** [comment]
> I guess this looks okay (no idea, TBH). The binder link you shared, does _not_ work for me, btw

Ha, interesting. Does it complain something specific or didn't it just start?

**Pull request merged**
