### PR TITLE
Don’t pass more than five percentiles to R5

### LINKED ISSUE #139: Maximum number of percentiles allowed is 5
Seems like R5 only allows a maximum of 5 percentiles. Would be something we should check on input (`len(percentiles) < 5`) and throw an error before the VM starts up to save folks time.

```
java.lang.java.lang.IllegalArgumentException: java.lang.IllegalArgumentException: Maximum number of percentiles allowed is 5
```

I can look into figuring out how to make this happen. Calling it a "bug" at this point but a mild one at that. Perhaps documentation?

### PR DESCRIPTION
**Pull request by christophfink**
closes #139

### CODE REVIEW

**Comment by christophfink** [comment]
Tests on Windows runners failed because geopandas needs fiona there (compare reopened issue #147 and PR #151

**Comment by christophfink** [comment]
@HTenkanen @wklumpen : you have been using geopandas on Windows, haven’t you? How do you ensure all dependencies are actually installed? mamba lists geopandas, fiona, pyogrio, gdal, libgdal, ..., as installed, but geopandas still fails to import fiona when trying to read a vector file, returning an error about not being able to find the ogrext DLL. Any clues?

**Comment by christophfink** [comment]
The error message is the following:

```
ImportError: DLL load failed while importing ogrext: The specified procedure could not be found.
```

**Comment by christophfink** [comment]
Now tried to reproduce the error on a local virtual machine with Windows, and there things work 🤯

**Comment by HTenkanen** [comment]
@christophfink : Umph, annoying issue.. 🤦🏻‍♂️ I found some discussion about this here, but don't have any ready solution for this: https://github.com/conda-forge/fiona-feedstock/issues/139#issuecomment-532597841

**Comment by christophfink** [comment]
> @christophfink : Umph, annoying issue.. 🤦🏻‍♂️ I found some discussion about this here, but don't have any ready solution for this: [conda-forge/fiona-feedstock#139 (comment)](https://github.com/conda-forge/fiona-feedstock/issues/139#issuecomment-532597841)

I’ve seen those older discussions (seems to crop up every couple of years), but nothing really recent. Not quite sure how to best debug this. Note that the env files work perfectly fine on a ‘normal’ Windows VM, off of GH runners.

**Comment by HTenkanen** [comment]
> > @christophfink : Umph, annoying issue.. 🤦🏻‍♂️ I found some discussion about this here, but don't have any ready solution for this: [conda-forge/fiona-feedstock#139 (comment)](https://github.com/conda-forge/fiona-feedstock/issues/139#issuecomment-532597841)
> 
> I’ve seen those older discussions (seems to crop up every couple of years), but nothing really recent. Not quite sure how to best debug this. Note that the env files work perfectly fine on a ‘normal’ Windows VM, off of GH runners.

I will test soon on my "real" Windows and see whether it reproduces the issue

**Comment by christophfink** [comment]
> > > @christophfink : Umph, annoying issue.. 🤦🏻‍♂️ I found some discussion about this here, but don't have any ready solution for this: [conda-forge/fiona-feedstock#139 (comment)](https://github.com/conda-forge/fiona-feedstock/issues/139#issuecomment-532597841)
> > 
> > 
> > I’ve seen those older discussions (seems to crop up every couple of years), but nothing really recent. Not quite sure how to best debug this. Note that the env files work perfectly fine on a ‘normal’ Windows VM, off of GH runners.
> 
> I will test soon on my "real" Windows and see whether it reproduces the issue

Thanks! (not much hope, to be honest, that you will be able to reproduce this)

**Comment by christophfink** [comment]
Slightly hopeful, that this is what causes the troubles: 

> If `environment-file` is used and you want that to be the environment used, you need to explicitely provide the name of that environment on `activate-environment`. 

https://github.com/conda-incubator/setup-miniconda/blob/main/action.yml#L85

**Comment by christophfink** [comment]
N

> Slightly hopeful, that this is what causes the troubles:
> 
> > If `environment-file` is used and you want that to be the environment used, you need to explicitely provide the name of that environment on `activate-environment`.
> 
> https://github.com/conda-incubator/setup-miniconda/blob/main/action.yml#L85

Nope, did not work.

**Comment by HTenkanen** [comment]
@christophfink FYI: I now asked about this issue from geopandas fellows here: https://gitter.im/geopandas/geopandas

**Comment by christophfink** [comment]
> > > > > @christophfink : Umph, annoying issue.. 🤦🏻‍♂️ I found some discussion about this here, but don't have any ready solution for this: [conda-forge/fiona-feedstock#139 (comment)](https://github.com/conda-forge/fiona-feedstock/issues/139#issuecomment-532597841)
> > > > 
> > > > 
> > > > I’ve seen those older discussions (seems to crop up every couple of years), but nothing really recent. Not quite sure how to best debug this. Note that the env files work perfectly fine on a ‘normal’ Windows VM, off of GH runners.
> > > 
> > > 
> > > I will test soon on my "real" Windows and see whether it reproduces the issue
> > 
> > 
> > Thanks! (not much hope, to be honest, that you will be able to reproduce this)
> 
> @christophfink : Yup, on my Windows machine everything works fine when I installed the environment. Perhaps it would be easiest if I ask from geopandas guys whether they know anything about this..

That would be great! 


I’m right now playing around with the github workflow definitions (kinda suspect that it’s somehow connected to the conda/miniforge github action, but that’s hard to debug); sorry (but not sorry) for force-pushing to main for this - there’s not really any other way to test things.

**Comment by christophfink** [comment]
Plot twist: it seems that it only happens withing pytest:

Screenshot from 2022-08-16 16-09-09
!

**Comment by HTenkanen** [comment]
> Plot twist: it seems that it only happens withing pytest:

Ooookay, super weird 😬

**Comment by christophfink** [comment]
And this way I can also reproduce it on my ‘local-ish’ windows! little success, at least :)

**Comment by HTenkanen** [comment]
@christophfink Hmm, could this be relevant (related to faulthandler)? https://github.com/pytest-dev/pytest/issues/7634#issuecomment-672804839

**Comment by wklumpen** [comment]
Not sure I have much to add here, other than I have gotten GeoPandas to work both through conda (worked flawlessly) and with vanilla pip (using specific archived wheels, `pipwin`, and hours of hair pulling). It doesn't surprise me though that there's some wonky stuff.

**Comment by jorisvandenbossche** [comment]
For reference, this is how we set up the environment in geopandas' CI (where we also install fiona, and don't see any problems with that):

https://github.com/geopandas/geopandas/blob/f5c89c63390d419eb4e5e760d3e120bc0989b753/.github/workflows/tests.yaml#L70-L76

Which seems very similar as what is done here. And afterwards, we also just call pytest on the geopandas tests, and don't have problems with fiona (I certainly regularly have run into pytest tricky issues when your _own_ package that you are testing has compiled code (which depends on how exactly you are invoking pytest, and from which directory, ...), but don't directly remember issues with not properly loading an installed package)

**Comment by christophfink** [comment]
> For reference, this is how we set up the environment in geopandas' CI (where we also install fiona, and don't see any problems with that):
> 
> https://github.com/geopandas/geopandas/blob/f5c89c63390d419eb4e5e760d3e120bc0989b753/.github/workflows/tests.yaml#L70-L76
> 
> Which seems very similar as what is done here. And afterwards, we also just call pytest on the geopandas tests, and don't have problems with fiona (I certainly regularly have run into pytest tricky issues when your _own_ package that you are testing has compiled code (which depends on how exactly you are invoking pytest, and from which directory, ...), but don't directly remember issues with not properly loading an installed package)

Although, upon looking at it more closely, you don’t seem to have fiona in your environment on Windows: https://github.com/geopandas/geopandas/runs/7869673672?check_suite_focus=true . That said, we have troubles importing `pyogrio`, as well, so not really a very good lead :D

**Comment by jorisvandenbossche** [comment]
> Although, upon looking at it more closely, you don’t seem to have fiona in your environment on Windows

You just by chance pointed to one build without fiona, but most others do have fiona included (all builds with "38-latest-conda-forge" don't have fiona on purpose to test this case as well, the other builds all have fiona)

**Comment by jorisvandenbossche** [comment]
Does removing "no:faulthandler" help? (xref https://github.com/r5py/r5py/pull/149#issuecomment-1216667322) (I personally would find it strange that it matters, but you never know ;))

**Comment by christophfink** [comment]
> Does removing "no:faulthandler" help? (xref [#149 (comment)](https://github.com/r5py/r5py/pull/149#issuecomment-1216667322)) (I personally would find it strange that it matters, but you never know ;))

Does not make any difference, unfortunately :/

**Comment by christophfink** [comment]
Alright, I have a better lead: It is clearly connected with the presence of OpenJDK. 

Could the people with access to ‘bare-metal’ Windows (@HTenkanen , @wklumpen ) please try to following minimum example:

1. Create an environment file `fionatest.yaml` with the following content:

```
name: fionatest

channels:
    - conda-forge

dependencies:
    - python=3.10
    - fiona
```

2. Use mamba to create a new environment using this file: 

```
mamba env create --file fionatest.yaml
```

3. try to import fiona (should be successful)

```
python -c "import fiona"
```

4. install openjdk (in this example using mamba, in the github runners we use the appropriate github action)

```
mamba install -y openjdk=11
```

5. try to import fiona, again (fails!)

```
python -c "import fiona"
```

6. Bonus step 1: uninstall the JDK

```
mamba remove -y openjdk
```

7. Bonus step 2: try to import fiona, again (STILL fails!)

```
python -c "import fiona"
```

Not quite sure how to get out of this, as we need *both* a JDK and fiona. At least I’m my semi-certain that it’s not pytest. I’m fairly sure that it’s somehow connected to environment variables (like %PATH%, e.g.), and that installing the JDK messes them up, apparently both with the GH action and from mamba. If you try the (hopefully reproducible) example, could you compar the environment variables (or at least %PATH%) before and after every step? (e.g., `python -c "import os; print(os.environ['PATH'])"`) Thanks!

**Comment by jorisvandenbossche** [comment]
GDAL _might_ check for the JAVA_HOME env variable (for some driver that depends on it), and that might be changed by installing openjdk?

**Comment by christophfink** [comment]
> GDAL _might_ check for the JAVA_HOME env variable (for some driver that depends on it), and that might be changed by installing openjdk?

Not (anymore) defined after removing OpenJDK ...

**Review by HTenkanen — APPROVED** [review]

**Pull request merged**
