### PR TITLE
Additional travel time window context (closes #339)

### LINKED ISSUE #339: Discuss `departure_time_window` in the documentation
See discussion in #304

### PR DESCRIPTION
**Pull request by wklumpen**
See #339 - Suggested language changes for `departure_time_window` nuance.

Marking this as work in progress until we have better resolution of discussion on #292 as this will affect the approach here.

### CODE REVIEW

**Comment by christophfink** [comment]
@wklumpen is this ready for review?

**Comment by wklumpen** [comment]
Take a look at #292 and let me know if you still feel comfortable with the suggested default

**Comment by christophfink** [comment]
Should we put it on hold for now? Or change the default value to something else, but keep the text you wrote for this PR because it explains the problem quite well?

**Comment by wklumpen** [comment]
I'm happy to merge it in and leave the default as-is while also reconsidering the default for the future.

**Review by christophfink — APPROVED** [review]
Looks good! Can you then maybe open a new issue to remind us that we should revisit this?

**Pull request merged**
