### PR TITLE
Check for unique ID columns in origins/destinations

### PR DESCRIPTION
**Pull request by christophfink**
See all comments in closed PR #141

### CODE REVIEW

**Comment by HTenkanen** [comment]
Let's continue discussion here, so [quoting myself](https://github.com/r5py/r5py/pull/141#issuecomment-1239311955)

@christophfink:
> Hmm, okay, it passed all the tests and didn't spot anything problematic, so what is the issue with the PR?

**Comment by christophfink** [comment]
also [quoting myself](https://github.com/r5py/r5py/pull/141#issuecomment-1239316084): 

> All the unresolved comments went straight into main!
> Removing them from this PR would also mean removing the code that added them.

You should have cherry-picked the lines that are alright, rather than straight-up accepting a pull request that still has (easily fixable) unresolved comments.

**Comment by HTenkanen** [comment]
> also [quoting myself](https://github.com/r5py/r5py/pull/141#issuecomment-1239316084):
> 
> > All the unresolved comments went straight into main!
> > Removing them from this PR would also mean removing the code that added them.
> 
> You should have cherry-picked the lines that are alright, rather than straight-up accepting a pull request that still has (easily fixable) unresolved comments.

Ahaa, okay sorry.. Didn't realize we are so "puristic" keeping the main clean. 😄 But fair enough, let's cherry-pick. I would have been okay improving the code-base later and hence created the issues.

**Comment by christophfink** [comment]
I’m at it, no worries :)

**Comment by christophfink** [comment]
I could not push to wklumpen:140-unique-id-columns for some reason, moving this to a different branch (this means a new PR: #165 )

**Pull request closed without merging**
